config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "users#show"
  resources :users do
    resources :contacts
  end
  patch "/update_contacted_at/:id" => "contacts#update_contacted_at", as: :update_contacted_at_for
  post '/update_form' => 'contacts#update_form'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :name, :contact_method, :last_contacted_on, presence: true

  CONTACT_METHODS = ["Phone", "Facetime", "FB Messenger", "What's App", "Text", "Email", "Other"]

  default_scope -> { order(last_contacted_on: :asc) }





  def contact!
    self.update_column(:last_contacted_on, Time.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @contact = Contact.new
    respond_to do |format|
      format.html
      format.js { }
    end
  end

  def create
    @user = User.find(params[:user_id])
    @contact = @user.contacts.new(contact_params)
    if @contact.save
      redirect_to user_path(@user), notice: "Contact created!"
    else
      render 'new'
    end
  end

  def update_contacted_at
    @contact = Contact.find(params[:id])
    @user = @contact.user
    @contact.contact!

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update_form
     respond_to do |format|
      format.js
    end
  end

  def show
    @contact = Contact.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def edit
    @user = User.find(params[:user_id])
    @contact = Contact.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end



  private

    def contact_params
      params.require(:contact).permit(:name, :phone, :contact_method, :handle, :last_contacted_on, :time_between_contact)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @contact = @user.contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper

  def should_contact(contact)
    if contact.last_contacted_on < contact.time_between_contact.days.ago
      "<span class='should-contact contact#{contact.id}'>#{time_ago_in_words(contact.last_contacted_on)} ago </span>".html_safe
    else
      "<span class='shouldnt-contact contact#{contact.id}'>#{time_ago_in_words(contact.last_contacted_on)} ago</span>".html_safe
    end
  end

    def contact(c)
      case c.contact_method
      when "Phone"
        link = "tel::#{c.phone}"
      when "Facetime"
        link = "facetime:#{c.phone}"
      when "FB Messenger"
        link = "https://www.facebook.com/#{c.handle}"
      when "What's App"
        link = "https://www.whatsapp.com/"
      when "text"
        link = "sms:#{c.phone}"
      when "Email"
        link = "mailto:#{c.handle}"
      when "Other"
        link = "https://www.whatsapp.com/"
      end
      return link
    end

    def i_did_it(c)
      c.contact!
    end
  end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.erb
<tr>
  <td>
    <span class='name'> <%= link_to @contact.name, user_contact_path(@contact.user, @contact) %> </span>
  </td>
  <td class='last_contacted'>
    <%= should_contact(@contact) %>
  </td>
  <td>
    <span class='contact-button'> <%= link_to "Contact", update_contacted_at_for_path(@contact), method: :patch, remote: true %> </span>
  </td>
</tr>

app/views/contacts/_create_form.html.erb
<div class='form-wrapper'>
  <div class="person-box">
    <%= image_tag("face.svg", class: "face-pic") %>
    <h2> Let's create a contact.</h2>
  </div>
  <div class='form'>

    <%= form_for(@contact, url: user_contacts_path(@user)) do |f| %>
      <%= render 'layouts/errors', object: f.object %>
        <ul>

          <li class="required name">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true %>
          </li>

          <li class="required contact-method">
            <%= f.label :contact_method %>
            <%= f.select :contact_method, Contact::CONTACT_METHODS, prompt: "Pick one", method: :patch, remote: true %>
          </li>

          <li class='required last'>
            <%= f.label :last_contacted_on %>
            <%= f.date_select :last_contacted_on %>
          </li>

          <li class='required often'>
            <%= f.label :how_often_do_you_want_to_contact_them? %>
            Every <%= f.number_field(:time_between_contact, in: 1..100) %> days
          </li>

          <li class="handle">
            <%= f.label :handle %>
            <%= f.text_field :handle %>
          </li>

          <li class="phone">
            <%= f.label :phone_number %>
            <%= f.text_field :phone %>
          </li>

        </ul>
        <div class="actions">
          <%= f.submit class: "btn-3d" %>
          <%= link_to "Cancel", user_path(@user), class: 'button' %>
        </div>
    <% end %>

  </div>

</div>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <%= render 'layouts/errors', object: f.object %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :contact_method %>
        <%= f.select :contact_method, Contact::CONTACT_METHODS, prompt: "Pick one" %>
      </li>
      <li class='required'>
        <%= f.label :last_contact_on %>
        <%= f.date_select :last_contacted_on %>
      </li>
      <li>
        <%= f.label :handle %>
        <%= f.text_field :handle %>
      </li>
      <li>
        <%= f.label :phone_number %>
        <%= f.text_field :phone %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", user_path(@user), class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/contacts/_update_form.html.erb
<div class='form-wrapper'>
  <div class="person-box">
    <%= image_tag("face.svg", class: "face-pic") %>
    <h2> Let's edit a contact.</h2>
  </div>

  <div class='form'>
    <%= form_for(@contact, url: user_contact_path(@user)) do |f| %>
      <%= render 'layouts/errors', object: f.object %>
        <ul>
          <li class="required name">
             <%= f.label :name %>
             <%= f.text_field :name, autofocus: true %>
           </li>

           <li class="required contact-method">
             <%= f.label :contact_method %>
             <%= f.select :contact_method, Contact::CONTACT_METHODS, prompt: "Pick one", method: :patch, remote: true %>
           </li>

           <li class='required last'>
             <%= f.label :last_contacted_on %>
             <%= f.date_select :last_contacted_on %>
           </li>

           <li class='required often'>
             <%= f.label :how_often_do_you_want_to_contact_them? %>
             Every <%= f.number_field(:time_between_contact, in: 1..100) %> days
           </li>

           <li class="handle">
             <%= f.label :handle %>
             <%= f.text_field :handle %>
           </li>

           <li class="phone">
             <%= f.label :phone_number %>
             <%= f.text_field :phone %>
           </li>
         </ul>

        <div class="actions">
          <%= f.submit %>
          <%= link_to "Cancel", user_path(@user), class: 'button' %>
        </div>
    <% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @contact.name %></h1>
</header>

<%= render 'update_form' %>

app/views/contacts/new.html.erb
<div class='signup-header'>
    <h1> Add new contact </h1>
</div>
  <%= render 'create_form' %>

app/views/contacts/show.html.erb
<ul>
  <li> <%= @contact.name %> </li>
  <li> <%= @contact.contact_method %> </li>
  <li> Last contacted on: <%= @contact.last_contacted_on.strftime("%A, %B %-d") %> </li>
  <% if @contact.handle %>
    <li> Handle: <%= @contact.handle %> </li>
  <% end %>
  <% if @contact.phone? %>
    <li> Phone number: <%= number_to_phone(@contact.phone, area_code: true) if !@contact.phone.empty? %> </li>
  <% end %>
</ul>
<%= link_to "Edit Contact", edit_user_contact_path(@user.id, @contact) %>

app/views/contacts/update_contacted_at.js.erb
$(".contact<%= @contact.id%>").html("<%= should_contact(@contact) %>");
$(".contact<%= @contact.id%>").css("background-color", "#a5ffc6");

window.location.href = "<%= contact(@contact) %>";

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="errors">
    <div class="error-explanation">
      The form contains <%= pluralize(object.errors.count + 1, "error") %>.
    </div>
    <ul class='errors-list'>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    <li> Sorry bro that sucks </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class='header'>
  <% if user_signed_in? %>

    <div class='account'>
      <div class='name'>
        <%= current_user.name %>
      </div>
      <div class='edit-account'>
        <%= link_to "Edit Account", edit_user_registration_path %>
      </div>
    </div>

    <div class='main'>
      <h1> <%= link_to "Keep In Touch", root_url %> </h1>
    </div>

    <div class='account-mobile'>
      <%= current_user.name %>
      <%= link_to "Edit Account", edit_user_registration_path %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </div>

    <div class='signout'>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </div>

  <% else %>

    <h1> <%= link_to "Keep In Touch", root_url %> </h1>

    <div class='signin'>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keepintouch</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1 id='yourcontacts'> Your contacts </h1>
<div class='add-new-contact'>
  <%= link_to "Add a new contact", new_user_contact_path(@user) %>
</div>
  <table class='headers'>
    <tr class='headers-row'>
      <th>Name</th>
      <th>Last Contacted</th>
      <th>Hit them up!</th>
    </tr>
  </table>
  <div class="contacts">
    <table>
      <div class='contacts-list'>
        <% @user.contacts.each do |c| %>
          <tr>
            <td>
              <span class='name'> <%= link_to c.name, user_contact_path(@user, c) %> </span>
            </td>
            <td class='last_contacted'>
              <%= should_contact(c) %>
            </td>
            <td>
              <span class='contact-button'> <%= link_to "Contact", update_contacted_at_for_path(c), method: :patch, remote: true %> </span>
            </td>
          </tr>
        <% end %>
      </div>
    </table>
  </div>
</div>